import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BriefcaseBusiness, CalendarDays, Heart, MessageCircle, Plus, Star, Users } from "lucide-react";
import { PortalTitle } from "@/components/jobira/portal-shell";
import { Button } from "@/components/ui/button";
import heroImage from "@/assets/jobira-hero.jpg";

const people = [["DK", "Daniel K.", "4.9", "London"], ["AR", "Amina R.", "4.8", "East London"], ["CP", "CleanPro Services", "4.9", "London"]];

export const Route = createFileRoute("/client/")({
  head: () => ({ meta: [{ title: "Client Dashboard | Jobira" }, { name: "description", content: "Manage jobs, bookings and trusted professionals on Jobira." }, { property: "og:title", content: "Client Dashboard | Jobira" }, { property: "og:description", content: "Manage jobs, bookings and trusted professionals on Jobira." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ClientOverview,
});

function ClientOverview() {
  return <><PortalTitle title="Hi, Sarah" description="Find trusted professionals and get the job done with confidence." action={<div className="flex gap-2"><Button asChild><Link to="/client/post-job"><Plus />Post a job</Link></Button><Button variant="outline" asChild><Link to="/professionals">Find professionals</Link></Button></div>} />
    <section className="dashboard-card relative min-h-52 overflow-hidden"><img src={heroImage} width={1600} height={1000} alt="Bright, welcoming interior" className="absolute inset-0 h-full w-full object-cover object-center dark:brightness-[.35]" /><div className="absolute inset-0 bg-[linear-gradient(90deg,var(--card),color-mix(in_oklab,var(--card)_90%,transparent)_46%,transparent)]" /><div className="relative max-w-lg p-7"><p className="section-kicker">Welcome back</p><h2 className="mt-3 font-display text-3xl font-semibold">Reliable professionals.<br />Happier spaces.</h2><p className="mt-3 text-sm text-muted-foreground">Your next trusted cleaner could be one conversation away.</p></div></section>
    <section className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[BriefcaseBusiness, "3", "Active jobs"], [Users, "12", "Saved professionals"], [CalendarDays, "2", "Upcoming bookings"], [Star, "4.9", "Average cleaner rating"]].map(([Icon, value, label]) => { const CardIcon = Icon as typeof BriefcaseBusiness; return <article key={String(label)} className="dashboard-card flex items-center gap-4 p-4"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-soft-green"><CardIcon className="h-4 w-4 text-brand-leaf" /></span><div><strong className="font-display text-xl">{String(value)}</strong><p className="text-xs text-muted-foreground">{String(label)}</p></div></article>; })}</section>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.5fr_0.7fr]"><section className="dashboard-card"><div className="flex items-center justify-between border-b border-border p-4"><h2 className="font-display font-semibold">Your recent jobs</h2><Button variant="link" size="sm" asChild><Link to="/client/jobs">View all <ArrowRight /></Link></Button></div>{[["Regular home clean", "Canary Wharf", "Active", "5 applications"], ["End of tenancy clean", "Stratford", "In progress", "Cleaner assigned"], ["Office clean (evening)", "Shoreditch", "Open", "3 applications"]].map((job) => <article key={job[0]} className="grid gap-3 border-b border-border p-4 last:border-b-0 sm:grid-cols-[1fr_auto] sm:items-center"><div><h3 className="text-sm font-semibold">{job[0]}</h3><p className="mt-1 text-xs text-muted-foreground">{job[1]} · Weekly</p></div><div className="flex items-center gap-3"><span className="rounded-sm bg-secondary px-2 py-1 text-xs">{job[2]}</span><Button size="sm" variant="outline">{job[3]}</Button></div></article>)}</section>
      <div className="space-y-4"><section className="dashboard-card p-5"><div className="flex items-center gap-3"><MessageCircle className="h-5 w-5 text-accent" /><h2 className="font-display font-semibold">Messages</h2></div>{[["Daniel K.", "I’m available this week."], ["CleanPro Services", "Thanks for the opportunity!"]].map(([name, message]) => <div key={name} className="mt-4 border-t border-border pt-3"><p className="text-xs font-semibold">{name}</p><p className="mt-1 text-xs text-muted-foreground">{message}</p></div>)}</section><section className="dashboard-card p-5"><Heart className="h-5 w-5 text-brand-leaf" /><h2 className="mt-3 font-display font-semibold">Build your trusted team</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">Save professionals you like and make rebooking even easier.</p><Button className="mt-4" size="sm" variant="outline" asChild><Link to="/professionals">Find professionals</Link></Button></section></div></div>
    <section className="dashboard-card mt-4 p-5"><div className="flex items-center justify-between"><h2 className="font-display font-semibold">Recommended professionals</h2><Button variant="link" size="sm" asChild><Link to="/professionals">View more <ArrowRight /></Link></Button></div><div className="mt-4 grid gap-3 md:grid-cols-3">{people.map(([initials, name, rating, location]) => <article key={name} className="rounded-md border border-border p-4"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-muted text-xs font-bold">{initials}</span><div><h3 className="text-sm font-semibold">{name}</h3><p className="text-xs text-muted-foreground">★ {rating} · {location}</p></div></div><Button className="mt-4 w-full" size="sm" variant="outline">View profile</Button></article>)}</div></section>
  </>;
}