import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, MapPin, PoundSterling } from "lucide-react";
import { DashboardShell } from "@/components/jobira/shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";

const steps = ["Role", "Details", "Requirements", "Preview"];

export const Route = createFileRoute("/post-job")({
  head: () => ({ meta: [{ title: "Post a Job | Jobira" }, { name: "description", content: "Create a clear Jobira opportunity and connect with suitable professionals." }, { property: "og:title", content: "Post a Job | Jobira" }, { property: "og:description", content: "Create a clear Jobira opportunity and connect with suitable professionals." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: PostJobPage,
});

function PostJobPage() {
  const [step, setStep] = useState(0);
  const [published, setPublished] = useState(false);
  const [form, setForm] = useState({ title: "Office Cleaning Professional", location: "Manchester city centre", type: "Part-time", pay: "18", description: "We’re looking for a reliable professional to care for two premium office spaces during weekday evenings.", requirements: "Commercial cleaning experience\nStrong attention to detail\nEligible to work in the UK" });
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  if (published) return <DashboardShell title="Your job is live." description="Professionals can now discover and apply to your opportunity."><section className="mx-auto mt-16 max-w-xl border border-border bg-card p-8 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-soft-green"><Check className="h-6 w-6 text-brand-leaf" /></div><h2 className="mt-5 font-display text-2xl font-semibold">Opportunity published</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">We’ll let you know as soon as suitable professionals apply.</p><div className="mt-7 flex justify-center gap-3"><Button variant="outline" asChild><Link to="/dashboard">Back to dashboard</Link></Button><Button onClick={() => { setPublished(false); setStep(0); }}>Post another</Button></div></section></DashboardShell>;
  return <DashboardShell title="Post a job" description="Create a clear opportunity in four short steps."><div className="mx-auto max-w-4xl"><ol className="grid grid-cols-4 border-b border-border">{steps.map((label, index) => <li key={label} className={`relative pb-4 text-center text-xs font-bold uppercase tracking-wider ${index <= step ? "text-foreground" : "text-muted-foreground"}`}><span className="block sm:hidden">{index + 1}</span><span className="hidden sm:block">{index + 1}. {label}</span>{index <= step && <span className="absolute inset-x-0 bottom-0 h-0.5 bg-primary" />}</li>)}</ol>
    <section className="mt-8 border border-border bg-card p-6 sm:p-8">
      {step === 0 && <div><p className="section-kicker">Step one</p><h2 className="mt-2 font-display text-2xl font-semibold">What role are you hiring for?</h2><div className="mt-8 space-y-6"><div><Label htmlFor="title">Job title</Label><Input id="title" className="mt-2 h-11" value={form.title} onChange={(event) => update("title", event.target.value)} /></div><div className="grid gap-5 sm:grid-cols-2"><div><Label htmlFor="location">Location</Label><div className="relative mt-2"><MapPin className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input id="location" className="h-11 pl-9" value={form.location} onChange={(event) => update("location", event.target.value)} /></div></div><div><Label htmlFor="type">Work type</Label><select id="type" className="mt-2 h-11 w-full rounded-md border border-input bg-background px-3 text-sm" value={form.type} onChange={(event) => update("type", event.target.value)}><option>Part-time</option><option>Full-time</option><option>Contract</option><option>One-off</option></select></div></div></div></div>}
      {step === 1 && <div><p className="section-kicker">Step two</p><h2 className="mt-2 font-display text-2xl font-semibold">Describe the opportunity.</h2><div className="mt-8 space-y-6"><div><Label htmlFor="pay">Hourly budget</Label><div className="relative mt-2 max-w-xs"><PoundSterling className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input id="pay" type="number" className="h-11 pl-9" value={form.pay} onChange={(event) => update("pay", event.target.value)} /></div></div><div><Label htmlFor="description">Job description</Label><Textarea id="description" className="mt-2 min-h-40" value={form.description} onChange={(event) => update("description", event.target.value)} /></div></div></div>}
      {step === 2 && <div><p className="section-kicker">Step three</p><h2 className="mt-2 font-display text-2xl font-semibold">What makes someone a good fit?</h2><div className="mt-8"><Label htmlFor="requirements">Requirements</Label><Textarea id="requirements" className="mt-2 min-h-48" value={form.requirements} onChange={(event) => update("requirements", event.target.value)} /><p className="mt-2 text-xs text-muted-foreground">Put each requirement on a new line.</p></div></div>}
      {step === 3 && <div><p className="section-kicker">Final review</p><h2 className="mt-2 font-display text-2xl font-semibold">Ready to meet the right person?</h2><div className="mt-8 border-y border-border py-6"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><h3 className="font-display text-xl font-semibold">{form.title || "Untitled role"}</h3><p className="mt-2 text-sm text-muted-foreground">{form.location} · {form.type}</p></div><strong className="text-lg">£{form.pay || "—"} / hour</strong></div><p className="mt-6 text-sm leading-7 text-muted-foreground">{form.description}</p><h4 className="mt-6 font-semibold">Requirements</h4><ul className="mt-3 space-y-2 text-sm text-muted-foreground">{form.requirements.split("\n").filter(Boolean).map((item) => <li key={item} className="flex gap-2"><Check className="h-4 w-4 text-brand-leaf" />{item}</li>)}</ul></div></div>}
      <div className="mt-9 flex justify-between border-t border-border pt-6"><Button variant="ghost" disabled={step === 0} onClick={() => setStep((current) => Math.max(0, current - 1))}><ArrowLeft />Back</Button>{step < 3 ? <Button onClick={() => setStep((current) => Math.min(3, current + 1))}>Continue<ArrowRight /></Button> : <Button onClick={() => setPublished(true)}>Publish job<Check /></Button>}</div>
    </section></div></DashboardShell>;
}