import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Building2, Check } from "lucide-react";
import { PublicShell } from "@/components/jobira/shell";
import { PageIntro, PricingCard } from "@/components/jobira/shared";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";

const plans = [
  { name: "Free", price: "£0", description: "Start your profile and explore Jobira at your own pace.", features: ["Apply to 5 jobs", "Cleaner profile", "Visible to clients", "Basic reputation", "Job alerts"] },
  { name: "Launch", price: "£15", description: "Everything you need to build momentum and win consistent work.", popular: true, features: ["Unlimited applications", "Priority in search", "Full reputation profile", "Client invitations", "Repeat bookings", "Email notifications", "Basic analytics"] },
  { name: "Standard", price: "£17.99", description: "More visibility, stronger tools and access to higher value opportunities.", features: ["Everything in Launch", "Featured listing", "Higher value jobs", "Client direct messaging", "Advanced alerts", "Performance insights", "Priority support"] },
  { name: "Premium", price: "£24.99", description: "Lead the market with maximum visibility and exclusive access.", features: ["Everything in Standard", "Top placement", "Exclusive client requests", "Early access", "Detailed analytics", "VIP badge"] },
];

export const Route = createFileRoute("/pricing")({ head: () => ({ meta: [{ title: "Simple Pricing | Jobira" }, { name: "description", content: "Straightforward Jobira plans from £0, with no long-term contract." }, { property: "og:title", content: "Simple Pricing | Jobira" }, { property: "og:description", content: "Straightforward Jobira plans from £0, with no long-term contract." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: PricingPage });

function PricingPage() { return <PublicShell><section className="section-pad border-b border-border"><div className="page-wrap"><PageIntro kicker="Plans for progress" title="Simple pricing. More opportunities." copy="Start free, upgrade when you’re ready, and change your plan whenever your needs change." centered /></div></section><section className="py-12"><div className="page-wrap grid gap-3 md:grid-cols-2 xl:grid-cols-4">{plans.map((plan) => <PricingCard key={plan.name} {...plan} />)}</div></section><section className="page-wrap py-12"><div className="border border-border bg-secondary p-6 sm:p-8"><div className="grid gap-7 lg:grid-cols-[1fr_1.4fr_auto] lg:items-center"><div className="flex items-center gap-4"><Building2 className="h-8 w-8 text-brand-leaf" /><div><p className="section-kicker">Cleaning Companies</p><h2 className="mt-1 font-display text-xl font-semibold">Built for growing teams</h2></div></div><div className="grid gap-2 text-sm sm:grid-cols-2">{["Add 3–5 cleaners", "Manage team profiles", "Team reputation tracking", "All professional features"].map((item) => <span className="flex items-center gap-2" key={item}><Check className="h-4 w-4 text-brand-leaf" />{item}</span>)}</div><Button variant="outline">View Company Plans <ArrowRight /></Button></div></div></section><section className="section-pad"><div className="page-wrap grid gap-12 lg:grid-cols-[0.7fr_1fr]"><div><p className="section-kicker">Questions, answered</p><h2 className="mt-4 font-display text-3xl font-semibold">Choose with confidence.</h2></div><Accordion type="single" collapsible className="border-t border-border">{([
  ["Can I change my plan later?", "Yes. You can upgrade or change your plan whenever your work needs change."],
  ["Is there a contract?", "No long-term contract. Paid plans renew monthly and can be cancelled before the next billing date."],
  ["Do you offer refunds?", "If you experience a billing issue, our support team will review it fairly and promptly."],
  ["What payment methods do you accept?", "We accept major debit and credit cards for all paid plans."],
] as [string, string][]).map(([question, answer]) => <AccordionItem key={question} value={question}><AccordionTrigger className="py-6 text-base">{question}</AccordionTrigger><AccordionContent className="pb-6 leading-6 text-muted-foreground">{answer}</AccordionContent></AccordionItem>)}</Accordion></div></section><section className="border-y border-border bg-secondary py-12"><div className="page-wrap grid grid-cols-3 divide-x divide-border text-center">{[["10K+", "Registered Cleaners"], ["4.8★", "Average Rating"], ["95%", "Would Hire Again"]].map(([stat, label]) => <div key={label} className="px-2"><strong className="font-display text-2xl sm:text-4xl">{stat}</strong><p className="mt-2 text-[0.65rem] uppercase tracking-wider text-muted-foreground sm:text-xs">{label}</p></div>)}</div></section></PublicShell>; }