import { useState } from "react";
import { AlertTriangle, BarChart3, CalendarCheck, Check, CheckCircle2, Clock3, CreditCard, Download, Eye, FileCheck2, Flag, MapPin, MessageCircle, MoreHorizontal, PoundSterling, Search, Settings, ShieldCheck, Star, TrendingUp, UserRound, Users, X } from "lucide-react";
import { MetricGrid, MiniChart, PortalTitle } from "./portal-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type JobRow = [string, string, string, string, string, string, string, string];
const jobs: JobRow[] = [
  ["#231", "End of tenancy clean", "John Smith", "London", "End of tenancy", "£120", "Open", "8"],
  ["#230", "Regular home clean", "Emma Patel", "Stratford", "Domestic", "£60", "Open", "3"],
  ["#229", "Airbnb turnover", "Michael Roberts", "Canary Wharf", "Airbnb", "£80", "Open", "11"],
  ["#228", "Office cleaning", "Sophie Lee", "Hackney", "Commercial", "£150", "In progress", "5"],
  ["#227", "Deep clean", "David Turner", "Ilford", "One-off", "£100", "Open", "4"],
  ["#226", "Weekly domestic clean", "Aisha Khan", "Barking", "Domestic", "£55", "Completed", "6"],
];

export function AdminJobsPage() {
  const [selected, setSelected] = useState(0);
  const [query, setQuery] = useState("");
  const [statuses, setStatuses] = useState<Record<string, string>>({});
  const visible = jobs.filter((job) => `${job[1]} ${job[2]} ${job[3]}`.toLowerCase().includes(query.toLowerCase()));
  const job = jobs[selected] ?? jobs[0];
  if (!job) return null;
  return <><PortalTitle title="Jobs" description="Review, edit, approve or remove every listing on the platform." />
    <MetricGrid items={[{ label: "Total jobs", value: "1,287", note: "↑ 14%", icon: FileCheck2, tone: "blue" }, { label: "Open jobs", value: "742", note: "↑ 22%", icon: CheckCircle2 }, { label: "In progress", value: "318", note: "↑ 6%", icon: Clock3, tone: "violet" }, { label: "Completed", value: "201", note: "↑ 12%", icon: ShieldCheck, tone: "blue" }, { label: "Reported", value: "26", note: "↓ 4%", icon: AlertTriangle, tone: "orange" }]} />
    <section className="dashboard-card mt-4 p-3"><div className="grid gap-3 lg:grid-cols-[1.6fr_repeat(4,1fr)_auto]"><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} className="pl-9" placeholder="Title, client or location..." /></label>{["All types", "All listings", "All statuses", "All locations"].map((label) => <select key={label} className="h-9 rounded-md border border-input bg-background px-3 text-xs"><option>{label}</option></select>)}<Button variant="outline" size="sm" onClick={() => setQuery("")}>Reset</Button></div></section>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1fr_320px]"><section className="dashboard-card overflow-hidden"><div className="flex items-center justify-between border-b border-border p-4"><h2 className="font-display font-semibold">Jobs ({visible.length})</h2><Button variant="outline" size="sm"><Download />Export</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[830px] text-left text-xs"><thead className="bg-muted text-muted-foreground"><tr><th className="px-4 py-3">#</th><th>Title</th><th>Client</th><th>Location</th><th>Type</th><th>Budget</th><th>Status</th><th>Applications</th><th className="pr-4 text-right">Actions</th></tr></thead><tbody>{visible.map((row) => { const index = jobs.indexOf(row); return <tr key={row[0]} onClick={() => setSelected(index)} className={index === selected ? "border-t border-border bg-secondary/60" : "border-t border-border hover:bg-muted/50"}><td className="px-4 py-3 font-semibold">{row[0]}</td><td className="font-semibold">{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td><td>{row[4]}</td><td>{row[5]}</td><td><span className="rounded-sm bg-soft-green px-2 py-1 text-brand-leaf">{statuses[row[0]] ?? row[6]}</span></td><td>{row[7]}</td><td className="pr-4 text-right"><Button size="icon" variant="ghost" aria-label={`Actions for ${row[1]}`}><MoreHorizontal /></Button></td></tr>; })}</tbody></table></div></section>
      <aside className="dashboard-card h-fit p-5 xl:sticky xl:top-24"><div className="flex items-center justify-between"><span className="rounded-sm bg-soft-green px-2 py-1 text-xs text-brand-leaf">{statuses[job[0]] ?? job[6]}</span><strong className="text-xs text-muted-foreground">{job[0]}</strong></div><h2 className="mt-4 font-display text-xl font-semibold">{job[1]}</h2><p className="mt-2 flex items-center gap-2 text-xs text-muted-foreground"><MapPin className="h-4 w-4" />{job[3]}</p><dl className="my-5 grid grid-cols-2 gap-3 border-y border-border py-4 text-xs"><dt className="text-muted-foreground">Type</dt><dd>{job[4]}</dd><dt className="text-muted-foreground">Budget</dt><dd>{job[5]}</dd><dt className="text-muted-foreground">Applications</dt><dd>{job[7]}</dd><dt className="text-muted-foreground">Client</dt><dd>{job[2]}</dd></dl><p className="text-xs leading-5 text-muted-foreground">Full service clean with supplies included. The client prefers a verified professional with strong recent reviews.</p><Button className="mt-5 w-full"><Eye />View job details</Button><Button className="mt-2 w-full" variant="outline" onClick={() => setStatuses((current) => ({ ...current, [job[0]]: "In review" }))}>Change status</Button><Button className="mt-2 w-full" variant="destructive" onClick={() => setStatuses((current) => ({ ...current, [job[0]]: "Removed" }))}>Remove listing</Button></aside></div>
  </>;
}

type ProfessionalRow = [string, string, string, string, string, string, string, string];
const professionals: ProfessionalRow[] = [
  ["SM", "Sarah M.", "Individual", "East London", "4.9", "248", "98%", "Active"], ["CP", "CleanPro Ltd", "Company", "London", "4.8", "312", "96%", "Active"], ["DK", "Daniel K.", "Individual", "Stratford", "4.8", "189", "97%", "Active"], ["ST", "Sparkle Team", "Company", "Barking", "4.7", "276", "95%", "Active"], ["MT", "Maria T.", "Individual", "Canary Wharf", "4.7", "164", "94%", "Active"], ["JR", "James R.", "Individual", "Hackney", "4.6", "142", "92%", "Active"],
];

export function AdminReputationPage() {
  const [selected, setSelected] = useState(0);
  const profile = professionals[selected] ?? professionals[0];
  if (!profile) return null;
  return <><PortalTitle title="Reputation" description="Review performance, ratings, verification status and moderation data." />
    <MetricGrid items={[{ label: "Professionals", value: "892", note: "↑ 14%", icon: Users, tone: "orange" }, { label: "Average rating", value: "4.6", note: "+0.2", icon: Star, tone: "orange" }, { label: "Verified", value: "721", note: "81%", icon: CheckCircle2 }, { label: "Completed jobs", value: "12,384", note: "↑ 28%", icon: CalendarCheck, tone: "blue" }]} />
    <div className="mt-4 grid gap-4 xl:grid-cols-[1fr_330px]"><section className="dashboard-card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border p-4"><div className="flex gap-4 text-xs font-semibold"><span className="text-accent">All professionals</span><span className="text-muted-foreground">Individuals</span><span className="text-muted-foreground">Companies</span></div><Button variant="outline" size="sm"><Download />Export</Button></div><div className="grid gap-3 p-3 md:grid-cols-[1.5fr_repeat(3,1fr)]"><Input placeholder="Search by name or location..." />{["All locations", "All types", "Reputation score"].map((label) => <select key={label} className="h-9 rounded-md border border-input bg-background px-3 text-xs"><option>{label}</option></select>)}</div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="bg-muted text-muted-foreground"><tr><th className="px-4 py-3">#</th><th>Name</th><th>Type</th><th>Location</th><th>Rating</th><th>Jobs</th><th>Completion</th><th>Status</th></tr></thead><tbody>{professionals.map((row, index) => <tr key={row[1]} onClick={() => setSelected(index)} className={selected === index ? "border-t border-border bg-secondary/60" : "border-t border-border hover:bg-muted/50"}><td className="px-4 py-3">{index + 1}</td><td><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-muted font-bold">{row[0]}</span><strong>{row[1]}</strong></div></td><td>{row[2]}</td><td>{row[3]}</td><td className="text-warning">★ {row[4]}</td><td>{row[5]}</td><td className="text-brand-leaf">{row[6]}</td><td><span className="rounded-sm bg-soft-green px-2 py-1 text-brand-leaf">{row[7]}</span></td></tr>)}</tbody></table></div></section>
      <aside className="dashboard-card h-fit p-5 xl:sticky xl:top-24"><div className="flex items-center gap-3"><span className="flex h-14 w-14 items-center justify-center rounded-full bg-secondary font-bold">{profile[0]}</span><div><h2 className="font-display font-semibold">{profile[1]}</h2><p className="text-xs text-muted-foreground">{profile[2]} · {profile[3]}</p></div></div><section className="mt-5 rounded-md border border-border p-4"><p className="text-xs font-semibold">Reputation score</p><div className="mt-2 flex items-end justify-between"><strong className="font-display text-3xl">{profile[4]} <small className="text-sm text-muted-foreground">/ 5.0</small></strong><span className="text-xs font-bold text-brand-leaf">+0.4</span></div></section><div className="mt-3 grid grid-cols-2 gap-2 text-xs">{[["Completed", profile[5]], ["Repeat clients", "72"], ["Completion", profile[6]], ["Response", "1.2h"]].map(([label, value]) => <div key={label} className="rounded-md border border-border p-3"><strong>{value}</strong><p className="mt-1 text-muted-foreground">{label}</p></div>)}</div><section className="mt-3 rounded-md border border-border p-4"><div className="flex justify-between"><strong className="text-xs">Verification</strong><span className="text-xs text-brand-leaf">3 of 3 verified</span></div>{["Identity", "Right to work", "DBS check"].map((item) => <p key={item} className="mt-3 flex items-center justify-between text-xs"><span>{item}</span><span className="flex items-center gap-1 text-brand-leaf"><Check className="h-3 w-3" />Verified</span></p>)}</section><Button className="mt-4 w-full" variant="outline">View full profile</Button><Button className="mt-2 w-full" variant="destructive">Suspend user</Button></aside></div>
  </>;
}

type AdminListPageProps = { kind: "bookings" | "payments" | "verification" };
type ConfigRow = string[];
type ListConfig = { title: string; description: string; metrics: [string, string][]; headers: string[]; rows: ConfigRow[] };
const adminListConfig: Record<AdminListPageProps["kind"], ListConfig> = {
  bookings: { title: "Bookings", description: "Track scheduled, completed and cancelled bookings.", metrics: [["Total bookings", "624"], ["Upcoming", "86"], ["Completed", "498"], ["Cancelled", "40"]], headers: ["Booking", "Client", "Professional", "Date", "Value", "Status"], rows: [["#BK-2048", "Sarah M.", "Daniel K.", "12 Aug, 10:00", "£60", "Confirmed"], ["#BK-2047", "Emma Patel", "CleanPro Ltd", "12 Aug, 13:30", "£95", "Pending"], ["#BK-2046", "John Smith", "Maria T.", "11 Aug, 09:00", "£120", "Completed"], ["#BK-2045", "Aisha Khan", "James R.", "10 Aug, 16:00", "£75", "Cancelled"]] },
  payments: { title: "Payments", description: "Monitor transactions, platform fees, refunds and payouts.", metrics: [["Gross volume", "£84.2k"], ["Platform fees", "£8.4k"], ["Pending payouts", "£12.6k"], ["Refunded", "£1.2k"]], headers: ["Transaction", "Customer", "Professional", "Date", "Amount", "Status"], rows: [["#TX-92841", "Sarah M.", "Daniel K.", "12 Aug 2026", "£60", "Paid"], ["#TX-92840", "Emma Patel", "CleanPro Ltd", "12 Aug 2026", "£95", "Processing"], ["#TX-92839", "John Smith", "Maria T.", "11 Aug 2026", "£120", "Paid"], ["#TX-92838", "Aisha Khan", "James R.", "10 Aug 2026", "£75", "Refunded"]] },
  verification: { title: "Verification", description: "Review identity, eligibility and background-check submissions.", metrics: [["Pending review", "28"], ["Verified", "721"], ["Needs action", "14"], ["Rejected", "9"]], headers: ["Applicant", "Type", "Submitted", "Documents", "Risk", "Status"], rows: [["Sarah M.", "Individual", "12 Aug 2026", "3 of 3", "Low", "Ready"], ["CleanPro Ltd", "Company", "12 Aug 2026", "4 of 5", "Low", "Pending"], ["Maria T.", "Individual", "11 Aug 2026", "2 of 3", "Medium", "Needs action"], ["James R.", "Individual", "10 Aug 2026", "3 of 3", "Low", "Ready"]] },
};

export function AdminListPage({ kind }: AdminListPageProps) {
  const config = adminListConfig[kind];
  const [selected, setSelected] = useState(0);
  const [resolved, setResolved] = useState<Record<number, string>>({});
  const icons = [CalendarCheck, CheckCircle2, Clock3, AlertTriangle];
  const row = config.rows[selected] ?? config.rows[0];
  if (!row) return null;
  return <><PortalTitle title={config.title} description={config.description} action={<Button variant="outline"><Download />Export</Button>} /><MetricGrid items={config.metrics.map(([label, value], index) => ({ label, value, note: index === 3 ? "↓ 4%" : "↑ 12%", icon: icons[index] ?? CheckCircle2, tone: index === 3 ? "orange" : index === 0 ? "blue" : "green" }))} /><section className="dashboard-card mt-4 p-3"><div className="grid gap-3 md:grid-cols-[1.7fr_repeat(3,1fr)_auto]"><Input placeholder={`Search ${config.title.toLowerCase()}...`} />{["All statuses", "All dates", "All locations"].map((label) => <select key={label} className="h-9 rounded-md border border-input bg-background px-3 text-xs"><option>{label}</option></select>)}<Button variant="outline" size="sm">Reset</Button></div></section><div className="mt-4 grid gap-4 xl:grid-cols-[1fr_300px]"><section className="dashboard-card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead className="bg-muted text-muted-foreground"><tr>{config.headers.map((header, index) => <th key={header} className={index === 0 ? "px-4 py-3" : "py-3"}>{header}</th>)}</tr></thead><tbody>{config.rows.map((item, index) => <tr key={item[0]} onClick={() => setSelected(index)} className={selected === index ? "border-t border-border bg-secondary/60" : "border-t border-border hover:bg-muted/50"}>{item.map((cell, cellIndex) => <td key={`${item[0]}-${cellIndex}`} className={cellIndex === 0 ? "px-4 py-4 font-semibold" : "py-4"}>{cellIndex === item.length - 1 ? <span className="rounded-sm bg-soft-green px-2 py-1 text-brand-leaf">{resolved[index] ?? cell}</span> : cell}</td>)}</tr>)}</tbody></table></div></section><aside className="dashboard-card h-fit p-5"><p className="section-kicker">Selected record</p><h2 className="mt-3 font-display text-lg font-semibold">{row[0]}</h2><dl className="mt-5 space-y-3 text-xs">{config.headers.slice(1).map((header, index) => <div key={header} className="flex justify-between border-b border-border pb-3"><dt className="text-muted-foreground">{header}</dt><dd className="font-semibold">{row[index + 1]}</dd></div>)}</dl><Button className="mt-5 w-full" onClick={() => setResolved((current) => ({ ...current, [selected]: kind === "verification" ? "Verified" : "Approved" }))}><Check />Approve</Button><Button className="mt-2 w-full" variant="outline">View details</Button></aside></div></>;
}

export function AdminReportsPage() {
  return <><PortalTitle title="Reports" description="Understand marketplace growth, quality and operational performance." action={<Button variant="outline"><Download />Export report</Button>} /><MetricGrid items={[{ label: "Gross value", value: "£84.2k", note: "↑ 18%", icon: PoundSterling, tone: "blue" }, { label: "Completion rate", value: "94.8%", note: "+2.1%", icon: TrendingUp }, { label: "Active clients", value: "356", note: "↑ 8%", icon: Users, tone: "violet" }, { label: "Open reports", value: "18", note: "↓ 12%", icon: Flag, tone: "orange" }]} /><section className="mt-4 grid gap-4 xl:grid-cols-[1.4fr_0.8fr]"><article className="dashboard-card p-5"><div className="flex justify-between"><div><h2 className="font-display font-semibold">Marketplace performance</h2><p className="text-xs text-muted-foreground">Completed bookings and revenue trend</p></div><span className="text-xs">Last 12 months</span></div><MiniChart bars /></article><article className="dashboard-card p-5"><h2 className="font-display font-semibold">Operational health</h2>{[["Successful matches", "91%"], ["Repeat booking rate", "38%"], ["Disputes resolved", "96%"], ["Average response", "1.8h"]].map(([label, value]) => <div key={label} className="mt-4 flex items-center justify-between border-b border-border pb-3 text-sm"><span className="text-muted-foreground">{label}</span><strong>{value}</strong></div>)}</article></section><section className="dashboard-card mt-4 p-5"><h2 className="font-display font-semibold">Downloadable reports</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{["Marketplace summary", "Trust & safety", "Revenue reconciliation"].map((name) => <article key={name} className="rounded-md border border-border p-4"><BarChart3 className="h-5 w-5 text-accent" /><h3 className="mt-3 text-sm font-semibold">{name}</h3><p className="mt-1 text-xs text-muted-foreground">Updated 29 Sep 2026</p><Button className="mt-4" size="sm" variant="outline"><Download />Download</Button></article>)}</div></section></>;
}

export function AdminMessagesPage() {
  const threads = [["SM", "Sarah M.", "Question about a booking", "10:24"], ["CP", "CleanPro Ltd", "Verification document", "09:11"], ["DK", "Daniel K.", "Payment clarification", "Yesterday"]];
  const [selected, setSelected] = useState(0);
  const [reply, setReply] = useState("");
  const [sent, setSent] = useState(false);
  const thread = threads[selected] ?? threads[0];
  if (!thread) return null;
  return <><PortalTitle title="Messages" description="Review support conversations and marketplace enquiries." /><div className="grid gap-4 lg:grid-cols-[300px_1fr]"><section className="dashboard-card overflow-hidden"><div className="border-b border-border p-3"><Input placeholder="Search conversations..." /></div>{threads.map((item, index) => <Button key={item[1]} variant="ghost" onClick={() => { setSelected(index); setSent(false); }} className={selected === index ? "h-auto w-full justify-start rounded-none bg-secondary p-4 text-left" : "h-auto w-full justify-start rounded-none border-b border-border p-4 text-left"}><span className="flex h-9 w-9 items-center justify-center rounded-full bg-muted text-xs font-bold">{item[0]}</span><span className="min-w-0 flex-1"><strong className="block truncate text-xs">{item[1]}</strong><small className="block truncate text-muted-foreground">{item[2]}</small></span><small>{item[3]}</small></Button>)}</section><section className="dashboard-card flex min-h-[560px] flex-col"><header className="flex items-center gap-3 border-b border-border p-4"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-secondary font-bold">{thread[0]}</span><div><h2 className="font-display font-semibold">{thread[1]}</h2><p className="text-xs text-muted-foreground">{thread[2]}</p></div></header><div className="flex-1 space-y-4 p-5"><div className="max-w-lg rounded-md bg-muted p-4 text-sm">Hi, I need some help with this request. Could someone review it for me?</div><div className="ml-auto max-w-lg rounded-md bg-secondary p-4 text-sm">Of course. I’m reviewing the details now and will confirm the next step shortly.</div>{sent && <div className="ml-auto max-w-lg rounded-md bg-secondary p-4 text-sm">{reply}</div>}</div><div className="flex gap-2 border-t border-border p-4"><Input value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Write a reply..." /><Button onClick={() => { if (reply.trim()) setSent(true); }}><MessageCircle />Send</Button></div></section></div></>;
}

export function AdminSettingsPage() {
  const [saved, setSaved] = useState(false);
  return <><PortalTitle title="Settings" description="Control marketplace defaults, moderation and notifications." /><div className="grid gap-4 xl:grid-cols-[220px_1fr]"><nav className="dashboard-card h-fit p-2">{["General", "Marketplace", "Notifications", "Moderation", "Security"].map((item, index) => <Button key={item} variant={index === 0 ? "secondary" : "ghost"} className="w-full justify-start"><Settings />{item}</Button>)}</nav><section className="dashboard-card p-6"><h2 className="font-display text-lg font-semibold">General settings</h2><p className="mt-1 text-xs text-muted-foreground">Core information shown across the Jobira platform.</p><div className="mt-6 grid gap-5 md:grid-cols-2"><label className="text-xs font-semibold">Platform name<Input className="mt-2" defaultValue="Jobira" /></label><label className="text-xs font-semibold">Support email<Input className="mt-2" defaultValue="support@jobira.example" /></label><label className="text-xs font-semibold">Default currency<select className="mt-2 h-9 w-full rounded-md border border-input bg-background px-3 font-normal"><option>GBP (£)</option></select></label><label className="text-xs font-semibold">Default timezone<select className="mt-2 h-9 w-full rounded-md border border-input bg-background px-3 font-normal"><option>Europe/London</option></select></label></div><div className="mt-6 space-y-3 border-t border-border pt-5">{["Require review for reported listings", "Notify admins about verification risks", "Send weekly marketplace summary"].map((item) => <label key={item} className="flex items-center justify-between rounded-md border border-border p-4 text-sm"><span>{item}</span><input type="checkbox" defaultChecked className="h-4 w-4 accent-primary" /></label>)}</div><div className="mt-6 flex items-center gap-3"><Button onClick={() => setSaved(true)}>Save changes</Button>{saved && <span className="text-xs text-brand-leaf">Settings saved</span>}</div></section></div></>;
}