/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ClientRouteImport } from './routes/client'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as PostJobRouteImport } from './routes/post-job'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProfessionalsRouteImport } from './routes/professionals'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminReputationRouteImport } from './routes/admin.reputation'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as ClientBookingsRouteImport } from './routes/client.bookings'
import { Route as ClientFavouritesRouteImport } from './routes/client.favourites'
import { Route as ClientJobsRouteImport } from './routes/client.jobs'
import { Route as ClientLocationsRouteImport } from './routes/client.locations'
import { Route as ClientPaymentsRouteImport } from './routes/client.payments'
import { Route as ClientPostJobRouteImport } from './routes/client.post-job'
import { Route as ClientReviewsRouteImport } from './routes/client.reviews'
import { Route as ClientSettingsRouteImport } from './routes/client.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const PostJobRoute = PostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalsRoute = ProfessionalsRouteImport.update({
  id: '/professionals',
  path: '/professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReputationRoute = AdminReputationRouteImport.update({
  id: '/reputation',
  path: '/reputation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AdminRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const ClientBookingsRoute = ClientBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ClientRoute,
} as any)
const ClientFavouritesRoute = ClientFavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => ClientRoute,
} as any)
const ClientJobsRoute = ClientJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => ClientRoute,
} as any)
const ClientLocationsRoute = ClientLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => ClientRoute,
} as any)
const ClientPaymentsRoute = ClientPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ClientRoute,
} as any)
const ClientPostJobRoute = ClientPostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => ClientRoute,
} as any)
const ClientReviewsRoute = ClientReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ClientRoute,
} as any)
const ClientSettingsRoute = ClientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ClientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/post-job': typeof PostJobRoute
  '/pricing': typeof PricingRoute
  '/professionals': typeof ProfessionalsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reputation': typeof AdminReputationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/client/bookings': typeof ClientBookingsRoute
  '/client/favourites': typeof ClientFavouritesRoute
  '/client/jobs': typeof ClientJobsRoute
  '/client/locations': typeof ClientLocationsRoute
  '/client/payments': typeof ClientPaymentsRoute
  '/client/post-job': typeof ClientPostJobRoute
  '/client/reviews': typeof ClientReviewsRoute
  '/client/settings': typeof ClientSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/post-job': typeof PostJobRoute
  '/pricing': typeof PricingRoute
  '/professionals': typeof ProfessionalsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reputation': typeof AdminReputationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/client/bookings': typeof ClientBookingsRoute
  '/client/favourites': typeof ClientFavouritesRoute
  '/client/jobs': typeof ClientJobsRoute
  '/client/locations': typeof ClientLocationsRoute
  '/client/payments': typeof ClientPaymentsRoute
  '/client/post-job': typeof ClientPostJobRoute
  '/client/reviews': typeof ClientReviewsRoute
  '/client/settings': typeof ClientSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/post-job': typeof PostJobRoute
  '/pricing': typeof PricingRoute
  '/professionals': typeof ProfessionalsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reputation': typeof AdminReputationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/client/bookings': typeof ClientBookingsRoute
  '/client/favourites': typeof ClientFavouritesRoute
  '/client/jobs': typeof ClientJobsRoute
  '/client/locations': typeof ClientLocationsRoute
  '/client/payments': typeof ClientPaymentsRoute
  '/client/post-job': typeof ClientPostJobRoute
  '/client/reviews': typeof ClientReviewsRoute
  '/client/settings': typeof ClientSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client'
    | '/coming-soon'
    | '/dashboard'
    | '/jobs'
    | '/post-job'
    | '/pricing'
    | '/professionals'
    | '/admin/applications'
    | '/admin/bookings'
    | '/admin/jobs'
    | '/admin/messages'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/reputation'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verification'
    | '/client/bookings'
    | '/client/favourites'
    | '/client/jobs'
    | '/client/locations'
    | '/client/payments'
    | '/client/post-job'
    | '/client/reviews'
    | '/client/settings'
    | '/admin/'
    | '/client/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coming-soon'
    | '/dashboard'
    | '/jobs'
    | '/post-job'
    | '/pricing'
    | '/professionals'
    | '/admin/applications'
    | '/admin/bookings'
    | '/admin/jobs'
    | '/admin/messages'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/reputation'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verification'
    | '/client/bookings'
    | '/client/favourites'
    | '/client/jobs'
    | '/client/locations'
    | '/client/payments'
    | '/client/post-job'
    | '/client/reviews'
    | '/client/settings'
    | '/admin'
    | '/client'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/client'
    | '/coming-soon'
    | '/dashboard'
    | '/jobs'
    | '/post-job'
    | '/pricing'
    | '/professionals'
    | '/admin/applications'
    | '/admin/bookings'
    | '/admin/jobs'
    | '/admin/messages'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/reputation'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verification'
    | '/client/bookings'
    | '/client/favourites'
    | '/client/jobs'
    | '/client/locations'
    | '/client/payments'
    | '/client/post-job'
    | '/client/reviews'
    | '/client/settings'
    | '/admin/'
    | '/client/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  ComingSoonRoute: typeof ComingSoonRoute
  DashboardRoute: typeof DashboardRoute
  JobsRoute: typeof JobsRoute
  PostJobRoute: typeof PostJobRoute
  PricingRoute: typeof PricingRoute
  ProfessionalsRoute: typeof ProfessionalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-job': {
      id: '/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof PostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionals': {
      id: '/professionals'
      path: '/professionals'
      fullPath: '/professionals'
      preLoaderRoute: typeof ProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reputation': {
      id: '/admin/reputation'
      path: '/reputation'
      fullPath: '/admin/reputation'
      preLoaderRoute: typeof AdminReputationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/bookings': {
      id: '/client/bookings'
      path: '/bookings'
      fullPath: '/client/bookings'
      preLoaderRoute: typeof ClientBookingsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/favourites': {
      id: '/client/favourites'
      path: '/favourites'
      fullPath: '/client/favourites'
      preLoaderRoute: typeof ClientFavouritesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/jobs': {
      id: '/client/jobs'
      path: '/jobs'
      fullPath: '/client/jobs'
      preLoaderRoute: typeof ClientJobsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/locations': {
      id: '/client/locations'
      path: '/locations'
      fullPath: '/client/locations'
      preLoaderRoute: typeof ClientLocationsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/payments': {
      id: '/client/payments'
      path: '/payments'
      fullPath: '/client/payments'
      preLoaderRoute: typeof ClientPaymentsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/post-job': {
      id: '/client/post-job'
      path: '/post-job'
      fullPath: '/client/post-job'
      preLoaderRoute: typeof ClientPostJobRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/reviews': {
      id: '/client/reviews'
      path: '/reviews'
      fullPath: '/client/reviews'
      preLoaderRoute: typeof ClientReviewsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/settings': {
      id: '/client/settings'
      path: '/settings'
      fullPath: '/client/settings'
      preLoaderRoute: typeof ClientSettingsRouteImport
      parentRoute: typeof ClientRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReputationRoute: typeof AdminReputationRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReputationRoute: AdminReputationRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientBookingsRoute: typeof ClientBookingsRoute
  ClientFavouritesRoute: typeof ClientFavouritesRoute
  ClientJobsRoute: typeof ClientJobsRoute
  ClientLocationsRoute: typeof ClientLocationsRoute
  ClientPaymentsRoute: typeof ClientPaymentsRoute
  ClientPostJobRoute: typeof ClientPostJobRoute
  ClientReviewsRoute: typeof ClientReviewsRoute
  ClientSettingsRoute: typeof ClientSettingsRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientBookingsRoute: ClientBookingsRoute,
  ClientFavouritesRoute: ClientFavouritesRoute,
  ClientJobsRoute: ClientJobsRoute,
  ClientLocationsRoute: ClientLocationsRoute,
  ClientPaymentsRoute: ClientPaymentsRoute,
  ClientPostJobRoute: ClientPostJobRoute,
  ClientReviewsRoute: ClientReviewsRoute,
  ClientSettingsRoute: ClientSettingsRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  ComingSoonRoute: ComingSoonRoute,
  DashboardRoute: DashboardRoute,
  JobsRoute: JobsRoute,
  PostJobRoute: PostJobRoute,
  PricingRoute: PricingRoute,
  ProfessionalsRoute: ProfessionalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
